### ISSUE TITLE
article21里放的不是demo47

### ISSUE THREAD

**Issue by fanfeiyangcn** [hyper0x/Golang_Puzzlers#12]
21 | panic函数、recover函数以及defer语句 （上）https://time.geekbang.org/column/article/40359
里面提到demo47，但文件夹里是demo55

**Comment by hyper0x** [comment]
由于后期极客时间的编辑又重新整理了文章，所以专栏里的文章序号与代码仓库里的序号不一致了，你可以参照这里做对应：https://github.com/hyper0x/Golang_Puzzlers/blob/master/mapping_table.md
