### ISSUE TITLE
sign长度应该等于max1

### ISSUE THREAD

**Issue by ShawnXueXue** [hyper0x/Golang_Puzzlers#3]
https://github.com/hyper0x/Golang_Puzzlers/blob/aa99ef98793f6bd80f402683d9dad57a17a91c8b/src/puzzlers/article22/q0/demo58.go#L28

下边的61行也应该循环max1次,从sign中取值

**Comment by hyper0x** [comment]
收到，做了写改进，已经提交上来了。
