### ISSUE TITLE
Some questions about panic

### ISSUE THREAD

**Issue by TCeason** [hyper0x/Golang_Puzzlers#4]
## Summary
在 [demo48](https://github.com/hyper0x/Golang_Puzzlers/blob/master/src/puzzlers/article19/q1/demo48.go) 中，说明了控制权会一级一级地沿着调用栈的反方向传播至顶端。我就把代码改了改，变成了python，发现是和go的传播方式是反着的。这两种方式只是设计思路的差异吗？还是说，因为我这段 python 是面向过程的，所以，就展示的是这样？

求郝大或者其他大神解答

## 代码展示

```python
#!/usr/bin/python
def main():
	print "Enter function main."
	caller1()
	print "Exit function main."

def caller1():
	print "Enter function caller1."
	caller2()
	print "Exit function caller1."

def caller2():
	print "Enter function caller2."
	s1 = [0, 1, 2, 3, 4]
	e5 = s1[5]
	print "Exit function caller2. " 

main()
```

> **这些是打印结果：**
Enter function main.
Enter function caller1.
Enter function caller2.
Traceback (most recent call last):
  File "demo48.py", line 18, in <module>
    main()
  File "demo48.py", line 4, in main
    caller1()
  File "demo48.py", line 9, in caller1
    caller2()
  File "demo48.py", line 15, in caller2
    e5 = s1[5]
IndexError: list index out of range

**Comment by hyper0x** [comment]
应该是设计思路上的问题吧。每个语言都会有自己的考虑。
