### ISSUE TITLE
【倍洽】GoHackers 项目当前人员已满

### ISSUE THREAD

**Issue by gogeof** [hyper0x/Golang_Puzzlers#6]
GoHackers 项目当前人员已满，劳烦大佬帮忙处理一下

**Comment by gogeof** [comment]
![image](https://user-images.githubusercontent.com/13129099/50571555-659ef200-0de8-11e9-960b-98a0d03d57ee.png)

**Comment by sauchye** [comment]
同上， 郝老师可以处理一下么 = =

**Comment by chenxull** [comment]
+1

**Comment by hyper0x** [comment]
之前已经联系倍洽，刷脸让他们帮我把人数上限提升了。现在又满了的话，我再去交涉一下。

**Comment by hyper0x** [comment]
经过BearyChat技术支持的努力，人数上限进一步上调了100。
