### ISSUE TITLE
第二十八讲的一个疑问

### ISSUE THREAD

**Issue by YanniHu1996** [hyper0x/Golang_Puzzlers#8]
老师，我有一个疑问（在极客时间以及提问过了，不过不知道您是否还维护那个专栏所以在这里向您提问），对于cond来说，每次只唤醒一个goruntine，如果这么goruntine发现消息不是自己想要的就会从新阻塞在wait函数中，那么真正需要这个消息的goruntine还会被唤醒吗？

**Comment by YanniHu1996** [comment]
唤醒用的cond的Signal方法

**Comment by hyper0x** [comment]
我已经在专栏里回答你了。这里我就关掉了。
